### ISSUE TITLE
8fps on 3070TI

### ISSUE THREAD

**Issue by Pro100rus32** [doleron/yolov5-opencv-cpp-python#8]
I installed opencv with CUDA with version 4.5.4
![image](https://user-images.githubusercontent.com/64806740/159753138-0d1feaee-1b5b-453a-93f0-cd0d3ac7def6.png)
I run the file **yolo.py**
![image](https://user-images.githubusercontent.com/64806740/159752352-82f6d62b-ddc0-4304-9771-e9ccfad00af9.png)
I get 8 - 10 fps, which is too low. I removed the imshow and the fps stayed at the same level. I have noticed that the video card has almost no load. The load is 3 - 6%. I also tried running a smaller model, but fps did not rise above 16.
![image](https://user-images.githubusercontent.com/64806740/159752596-ecb7888d-742f-4841-96e3-dbaf358fc53a.png)
I ran this on the CPU as well, and got about 4 fps. I tried to run the second script, but it didn't work.
```
Traceback (most recent call last):
  File "C:\Users\test\Desktop\yolov5-opencv-cpp-python-main\yolo-tiny.py", line 19, in <module>
    input_image = format_yolov5(image) # making the image square
  File "C:\Users\test\Desktop\yolov5-opencv-cpp-python-main\yolo-tiny.py", line 12, in format_yolov5
    row, col, _ = frame.shape
AttributeError: 'NoneType' object has no attribute 'shape'
```

**How can I improve the speed?**

**Comment by freedomcoming** [comment]
Do you use cuda to run the script？
like this:
  cd yolov5-opencv-cpp-python
  python python/yolo.py cuda

**Comment by Pro100rus32** [comment]
> Do you use cuda to run the script？ like this: cd yolov5-opencv-cpp-python python python/yolo.py cuda

Yes. I have 140fps on yolov4 script, but yolov5 working in 10 fps : (

**Comment by fatandfat** [comment]
I found simply change 
`result.setPreferableTarget(dnn::DNN_TARGET_CUDA_FP16);` in `load_net()` to `result.setPreferableTarget(dnn::DNN_TARGET_CUDA);` 
will solve the low fps problem

**Comment by doleron** [comment]
Sorry, bro. I only tested it on note with RTX 2080. I'd keep it out to make easier reach by someone with same issue.
